### ISSUE TITLE
'user.User' that has not been installed

### ISSUE THREAD

**Issue by sunnythree** [cyclades1/Rental#9]
F:\github\Rental\venv\Scripts\python.exe F:\github\Rental\manage.py runserver 
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "F:\github\Rental\venv\lib\site-packages\django\apps\registry.py", line 158, in get_app_config
    return self.app_configs[app_label]
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\auth\__init__.py", line 170, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL, require_ready=False)
  File "F:\github\Rental\venv\lib\site-packages\django\apps\registry.py", line 208, in get_model
    app_config = self.get_app_config(app_label)
  File "F:\github\Rental\venv\lib\site-packages\django\apps\registry.py", line 165, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'user'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "F:\github\Rental\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "F:\github\Rental\venv\lib\site-packages\django\core\management\commands\runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "F:\github\Rental\venv\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "F:\github\Rental\venv\lib\site-packages\django\core\management\__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "F:\github\Rental\venv\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "F:\github\Rental\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "F:\github\Rental\venv\lib\site-packages\django\apps\registry.py", line 124, in populate
    app_config.ready()
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\admin\apps.py", line 27, in ready
    self.module.autodiscover()
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\admin\__init__.py", line 50, in autodiscover
    autodiscover_modules("admin", register_to=site)
  File "F:\github\Rental\venv\lib\site-packages\django\utils\module_loading.py", line 58, in autodiscover_modules
    import_module("%s.%s" % (app_config.name, module_to_search))
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\auth\admin.py", line 6, in <module>
    from django.contrib.auth.forms import (
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\auth\forms.py", line 18, in <module>
    UserModel = get_user_model()
  File "F:\github\Rental\venv\lib\site-packages\django\contrib\auth\__init__.py", line 176, in get_user_model
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'user.User' that has not been installed

how can i fix it?

**Comment by cyclades1** [comment]
This is resolve with latest changes
https://github.com/cyclades1/Rental/pull/12
